config/routes.rb
Reible::Application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts do 
    resources :reverts, :controller => 'post_reverts'
  end
  resources :nodes do 
    resources :posts, :controller => 'node_posts'
  end
  resources :admin
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    # => 
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       elsif user.name?  
         can [:read, :create], Post
         can :update, Post do |post|
         post.user_id == user.id
         end
       else
         can :read, Post
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :posts
  attr_accessible :name
  validates_presence_of :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :node
  has_many :reverts
  has_attached_file :avatar 
  attr_accessible :content, :revert_id, :title, :user_id,
  :node_id, :avatar
  validates_presence_of :content, :user_id
end

app/models/revert.rb
class Revert < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :content, :post_id, :user_id
  validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :reverts
  has_attached_file :photo   
            
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :photo, :admin
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def postadmin
    @post = Post.page(params[:page]).per(5).order("id DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to new_user_session_path, :alert => exception.message
  end
end

app/controllers/node_posts_controller.rb
class NodePostsController < ApplicationController
  before_filter :find_node
  def index
    @post = @node.posts.page(params[:page]).per(5)
  end

  protected
  def find_node
    @node = Node.find(params[:node_id]) 
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  load_and_authorize_resource
  def index
    @node = Node.all
  end

  def new
    @node = Node.new
  end

  def create
    @node = Node.create(params[:node])
    redirect_to :action => :index
  end

  def show
    @node = Node.find(params[:id])
  end

  def edit
    @node = Node.find(params[:id])
  end

  def update
    @node = Node.find(params[:id])
    @node.update_attributes(params[:node])

    redirect_to nodes_path
  end

  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    redirect_to nodes_path
  end
end

app/controllers/post_reverts_controller.rb
class PostRevertsController < ApplicationController
  before_filter :find_post
  def new
    if current_user == nil
      redirect_to new_user_session_path
    else
    @revert = Revert.new
    end
  end

  def create
    @revert = Revert.create(:content => params[:revert][:content], 
      :user_id => current_user.id, :post_id => @post.id)
    if @revert.save
      redirect_to post_path(:id => @post.id)
    else
      redirect_to posts_path
    end
  end

  protected
  def find_post
    @post = Post.find( params[:post_id] )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @post = Post.page(params[:page]).per(5).order("id DESC")
    @node =Node.all
  end

  def new
    @post = Post.new

  end

  def create
    @post = current_user.posts.create(params[:post])
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @revert = Revert.where(:post_id => @post.id).all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
end
  

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/node_posts_helper.rb
module NodePostsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/post_reverts_helper.rb
module PostRevertsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span5 offset4" style="border: 1px solid #fff;  padding 20px; background-color: #FFFFFF">
          <div style ="padding-left: 20%">
            <h2><%= "admin"%></h2>
            <p>
              <strong>
                <%= link_to 'node', nodes_path%>
              </strong>
            </p>
            <p>
              <strong>
                <%= link_to 'posts', posts_path%>
              </strong>
            </p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar center">
  <div class="navbar-inner" >
    <a class="brand text-left">Tule</a>
    <ul class="nav">
      <li  >
        <%= link_to '首页', root_path%>
      </li>
    </ul>
    <div style="padding-left: 74%">
      <% if signed_in? %>
      <li class="brand">
        <%= current_user.name %>|
      </li>
      <%= link_to "|退出", destroy_user_session_path, method: "delete", class: "brand"%>
      <% else %>
        <%= link_to '帐号登录', new_user_session_path, 
        class: "brand"%>
        <%= link_to '帐号注册', new_user_registration_path, 
        class: "brand"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tule-回归论坛最初的美丽</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body style="background-color: #ccc;">
    <%= render 'layouts/header' %>

    <%= yield %>

  </body>
</html>

app/views/node_posts/index.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10" style="background-color: #FFFFFF">
        <!--Sidebar content-->
        
        <legend>
            <strong style="padding-left: 1%">
                <%= link_to '首页', root_path%>
                /<%= @node.name%>
            </strong>
            
            <strong style="padding-left: 72%">
            <% if current_user == nil %>
                
                <% else %>
                <%= link_to '发表新帖子', new_post_path, class: "btn btn-success" %>
            <% end %>
            </strong>
        </legend>
            <% @post.each do |p|%>
                <legend style="padding-left: 1%">
                    <p class="muted">
                        <%=link_to p.title, post_path(p)%>
                    </p>
                    <p>
                        <%= t("index.revertnum")%>
                        <%= p.reverts.count %>
                        </p>
                    <p>
                        <small>
                            发表时间:<%=p.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %>
                        </small>

                        <%if p.reverts.last == nil %>
                            <p></p>
                        <%else%>
                        <small>
                            <%= t("index.last")%>:
                            <%= User.find(Revert.where(:post_id => p.id).last.user_id).name%>

                        </small>
                        <%end%>
                    </p>
                </legend>
            <% end %>
            <%= paginate @post %>
        </div>

               <div class="span2" style="background-color: #FFFFFF">
    <!--Body content-->
            <% if signed_in? %>
                <p><%= image_tag current_user.photo.url%></p>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                用户:<%= current_user.name %>
                </p>
                <p style="padding-left: 1%">
                光临Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
                <p>
                </p>
            <% else %>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                <%= link_to '登录', new_user_session_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                <%= link_to '注册', new_user_registration_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/nodes/edit.html.erb
<div class="row">
  <div class="span3 offset7">
    <%= form_for @node, :url => { :controller => 'nodes', :action => 'update', :id => @node } do |f| %>
    <%= f.label :name, t("index.name") %>
    <%= f.text_field :name %>
    <%= f.submit, t("index.update") %>
    <% end %>
  </div>
</div>

app/views/nodes/index.html.erb
<div class="row" >
    <ul class="span3 offset2">
      <% @node.each do |node| %>
      <li>
      <%= node.name %>
      <%= link_to t("index.update"), :controller => 'nodes', :action => 'edit', :id => node %>
      <%= link_to t("index.delete"), node_path(node),:method => :delete%>
      </li>
     <% end %>
    </ul>
    <%= link_to t("index.createnode"), new_node_path%>
</div>

app/views/nodes/new.html.erb
<div class="row">
  <div class="span3 offset7">
    <%= form_for @node do |n|%>
    <%= n.label :name, t("index.createnode") %>
    <%= n.text_field :name %>
    <%= n.submit t("index.createnode") %>
    <% end %>
    <%= link_to t("index.nodelist"), nodes_path, class: "btn btn-info"%>
</div>
</div>

app/views/post_reverts/new.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3 offset4" style="border: 1px solid #fff;  padding 20px; background-color: #FFFFFF">
          <div style ="padding-left: 20%">
<%= form_for @revert, :url => post_reverts_path(@post) do |r| %>
  <%= r.label :content, t("index.content")%>
  <%= r.text_area :content %>
  <p><%= r.submit t("index.revert") %>
<% end %>
        </div>
      </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container" style="padding-left: 30%;">
  <div class="row">
    <%= form_for @post, :url => { :controller => 'posts', :action => 'update', :id => @post } do |post| %>
    <%= t("index.node")%>
    <%= post.select :node_id, Node.all.map { |c| [c.name, c.id] }%>
    <%= post.label :title, t("index.titlep")%>
    <%= post.text_field :title, class: "span7" %>
    <%= post.label :content, t("index.content")%>
    <%= post.text_area :content, class: "span7" %>
    <p><%= t("index.img")%></p>
    <p><%= post.file_field :avatar%> </p> 
    <%= post.submit t("index.update") %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10" style="background-color: #FFFFFF">
        <!--Sidebar content-->
        <!--22222222222222222222222-->
            <div class="row-fluid">
                <div class = "span4">
                    <strong class="brand text-left" style="font-size: 25px; padding-left:1% ">
                        Tule
                    </strong>
                    -<%= t("index.title")%>
                </div>
                <div class = "span2 offset6">
                    <strong class="text-right">
                    <%= link_to t("index.new"), new_post_path, class: "btn btn-success" %>
                    </strong>
                </div>
            </div>
            <legend></legend>
    <!--first line end-->
            <% @post.each do |p|%>
                <legend>
                    <div class="row-fluid">
                        <div class = "span8">
                            <%= link_to p.title, post_path(p), style: "padding-left: 1%"%>
                        </div>
                        <!--title End-->
                        <div class = "span2">
                        <%if current_user == nil%>
                        <%elsif current_user.admin?%>
                        <small>
                            <%= link_to t("index.delete"), post_path(p),:method => :delete, class: "brand"%>
                            <%= link_to t("index.update"), :controller => 'posts', :action => 'edit', :id => p %>
                        <%elsif current_user.id == p.user_id %>
                        <%= link_to t("index.update"), :controller => 'posts', :action => 'edit', :id => p %>
                        <%else%>
                        <%end%>
                        </small>
                        </div>
                        <div class = "span2">
                        <%= t("index.revertnum")%>
                        <%= p.reverts.count %>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <small>
                            <%= t("index.createtime")%>:<%=p.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %>
                        </small>
                        <small>
                            <%= t("index.user")%>:<%= p.user.name%>
                        </small>
                        <%if p.reverts.last == nil %>
                            <p></p>
                        <%else%>
                        <small>
                            <%= t("index.last")%>:
                            <%= User.find(Revert.where(:post_id => p.id).last.user_id).name%>
                        </small>
                        <%end%>
                    </div>
                </legend>
            <% end %>
            <!--table END-->
            <div class="text-center">
            <%= paginate @post %>
            </div>
        </div>
<!--END LEFT-->

        <div class="span2" style="background-color: #FFFFFF">
    <!--Body content-->
            <% if signed_in? %>
                <p><%= image_tag current_user.photo.url%></p>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                用户:<%= current_user.name %>
                </p>
                <p style="padding-left: 1%">
                光临Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
            <% else %>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                <%= link_to '登录', new_user_session_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                <%= link_to '注册', new_user_registration_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
            <% end %>
        </div>
    </div>
</div>

<!--NODE-->

<div class="container-fluid" >
    <div class="row-fluid">
        <div class="span10" style="background-color: #FFFFFF">
            <div style="padding-left: 1%">
            <p><%= t("index.node")%></p>
        <% @node.each do |n|%>
        <%= link_to n.name, node_posts_path(n)%>
        &nbsp
        <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container" style="padding-left: 30%;">
  <div class="row">
    <%= form_for @post do |post| %>
    <%= t("index.node")%>
     <%= post.select :node_id, Node.all.map { |c| [c.name, c.id] }%>
	   <%= post.label :title, t("index.titlep")%>
	   <%= post.text_field :title, class: "span7" %>
	   <%= post.label :content, t("index.content")%>
     <%= post.text_area :content, class: "span7" %>
     <p>
        <%= t("index.img")%>
     </p>
     <p><%= post.file_field :avatar%> </p> 
     <p>
     <%= post.submit t("index.new"), class: "btn btn-primary" %>
     </p>
    <% end %>
  </div> 
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10" style="background-color: #FFFFFF">
    <!--Sidebar content-->
        <legend style="padding-left: 1%">
          <%= @post.title%>
          <p>
            <small>
              <%= t("index.user")%>:<%=@user.name%> 
              <%= t("index.createtime")%>:<%=@post.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %>
            </small> 
          </p>
        </legend>
        <p style="padding-left: 1%; padding-bottom: 30px">
          <p style="padding-left: 1%; padding-bottom: 30px">
            <%= @post.content%></p>
          <% if @post.avatar_file_name == nil %>
          <p></p>
          <% else %>
          <p><%= image_tag @post.avatar.url %></p>
          <% end %>
          </p>
        <legend></legend>
        <p style="padding-left: 1%">
        <%= link_to t("index.revert"), 
          new_post_revert_path(@post), 
          class: "btn btn-large btn-primary" %>
        </p>
        <legend></legend>
        <legend></legend>
        <!--revert-->
        <% num = 0 %>
        <% @revert.each do |r| %>
        <legend>
          <small style="padding-left: 1%">
            <%= num = num + 1%><%= t("index.row")%>
          </small>
        </legend>
        <legend style="padding-left: 1%">
          <%= r.content%>
        </legend>
        <small style="padding-left: 1%">
          <%= t("index.user")%>:
          <%= r.user.name%>
          <%= t("index.createtime")%>:
          <%= r.user.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %>
        </small>
        <% end %>
    <!--revertEnd-->
    </div>

        <div class="span2" style="background-color: #FFFFFF">
    <!--Body content-->
            <% if signed_in? %>
                <p><%= image_tag current_user.photo.url%></p>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                用户:<%= current_user.name %>
                </p>
                <p style="padding-left: 1%">
                光临Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
                <p>
                </p>
            <% else %>
                <p style="padding-left: 1%">
                欢迎
                </p>
                <p style="padding-left: 1%">
                <%= link_to '登录', new_user_session_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                <%= link_to '注册', new_user_registration_path, 
                class: "brand"%>
                </p>
                <p style="padding-left: 1%">
                Tule---论坛
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最搞笑的图片!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最动听的音乐!
                </p>
                <p style="padding-left: 1%">
                这里有:
                </p>
                <p style="padding-left: 1%">
                最带感的新闻!
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>